# Generated by Django 6.0.1 on 2026-01-29 18:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={
                "ordering": ["order"],
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
            },
        ),
        migrations.AlterModelOptions(
            name="trainingplan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Training Plan",
                "verbose_name_plural": "Training Plans",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration in seconds (for time-based exercises)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="muscle_group",
            field=models.CharField(
                choices=[
                    ("chest", "Chest"),
                    ("back", "Back"),
                    ("shoulders", "Shoulders"),
                    ("biceps", "Biceps"),
                    ("triceps", "Triceps"),
                    ("legs", "Legs"),
                    ("core", "Core"),
                    ("full_body", "Full Body"),
                    ("cardio", "Cardio"),
                ],
                default="full_body",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="reps",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of reps (null for time-based exercises)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="rest_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Rest time between sets in seconds",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(600),
                ],
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="sets",
            field=models.PositiveIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="target_weight",
            field=models.FloatField(
                blank=True, help_text="Target weight in kg", null=True
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="category",
            field=models.CharField(
                choices=[
                    ("strength", "Strength"),
                    ("cardio", "Cardio"),
                    ("flexibility", "Flexibility"),
                    ("mixed", "Mixed"),
                    ("hiit", "HIIT"),
                    ("yoga", "Yoga"),
                ],
                default="mixed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="duration_weeks",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Duration in weeks",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(52),
                ],
            ),
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="sessions_per_week",
            field=models.PositiveIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="trainingplan",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserPlanAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="plans.trainingplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Plan Assignment",
                "verbose_name_plural": "User Plan Assignments",
                "unique_together": {("user", "plan", "start_date")},
            },
        ),
    ]
