# Generated by Django 6.0.1 on 2026-01-29 18:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_alter_exercise_options_alter_trainingplan_options_and_more"),
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exerciseresult",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Exercise Result",
                "verbose_name_plural": "Exercise Results",
            },
        ),
        migrations.AlterModelOptions(
            name="workoutsession",
            options={
                "ordering": ["-scheduled_date"],
                "verbose_name": "Workout Session",
                "verbose_name_plural": "Workout Sessions",
            },
        ),
        migrations.RemoveField(
            model_name="workoutsession",
            name="date",
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="distance_meters",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Distance in meters (for cardio exercises)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration in seconds (for time-based exercises)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="exercise_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="sets_completed",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(50)]
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="calories_burned",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link to a training plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workout_sessions",
                to="plans.trainingplan",
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="User's rating of the workout (1-5)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="scheduled_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the workout is scheduled",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("skipped", "Skipped"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="exerciseresult",
            name="exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="results",
                to="plans.exercise",
            ),
        ),
        migrations.AlterField(
            model_name="exerciseresult",
            name="reps",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total reps or reps per set",
                null=True,
                validators=[django.core.validators.MaxValueValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="exerciseresult",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_results",
                to="workouts.workoutsession",
            ),
        ),
        migrations.AlterField(
            model_name="exerciseresult",
            name="weight",
            field=models.FloatField(blank=True, help_text="Weight in kg", null=True),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration in minutes",
                null=True,
                validators=[django.core.validators.MaxValueValidator(600)],
            ),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
